"""AI 提示词模板包（中文注释）。

本包用于集中管理所有 Agent 及 LLM 相关的提示词模板。
"""

from app.ai.prompts.agent_prompts import CHAT_AGENT_SYSTEM_PROMPT
from app.ai.prompts.common_prompts import (
    INTENT_CLASSIFY_PROMPT,
    TODO_PARAM_EXTRACT_PROMPT,
    QUERY_PARAM_EXTRACT_PROMPT,
    CHART_PARAM_EXTRACT_PROMPT
)
from app.ai.prompts.todo_prompts import (
    TODO_CLARIFY_PROMPT,
    TODO_DECOMPOSE_PROMPT,
    TODO_INTENT_ANALYZE_PROMPT,
    TODO_AGENT_SYSTEM_PROMPT
)
from app.ai.prompts.judge_prompts import (
    OUTPUT_JUDGE_PROMPT,
    DETAILED_JUDGE_PROMPT
)
from app.ai.prompts.knowledge_prompts import KNOWLEDGE_AGENT_SYSTEM_PROMPT

__all__ = [
    "CHAT_AGENT_SYSTEM_PROMPT",
    "INTENT_CLASSIFY_PROMPT",
    "TODO_PARAM_EXTRACT_PROMPT",
    "QUERY_PARAM_EXTRACT_PROMPT",
    "CHART_PARAM_EXTRACT_PROMPT",
    "TODO_CLARIFY_PROMPT",
    "TODO_DECOMPOSE_PROMPT",
    "TODO_INTENT_ANALYZE_PROMPT",
    "TODO_AGENT_SYSTEM_PROMPT",
    "OUTPUT_JUDGE_PROMPT",
    "DETAILED_JUDGE_PROMPT",
    "KNOWLEDGE_AGENT_SYSTEM_PROMPT",
]

