#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd -P)"
cd "$ROOT_DIR"

eval "$(bash scripts/vk_ports.sh --export)"

RUN_DIR="$ROOT_DIR/.vibe/run"
mkdir -p "$RUN_DIR"

PRIMARY_WORKTREE="$(git worktree list --porcelain | awk '/^worktree /{print $2; exit}')"

copy_if_missing() {
  local src_file="$1"
  local dst_file="$2"
  if [[ ! -f "$dst_file" && -f "$src_file" ]]; then
    cp "$src_file" "$dst_file"
    echo "[vk_setup] copied: $src_file -> $dst_file"
  fi
}

if [[ -n "$PRIMARY_WORKTREE" && "$PRIMARY_WORKTREE" != "$ROOT_DIR" ]]; then
  copy_if_missing "$PRIMARY_WORKTREE/.env.dev" "$ROOT_DIR/.env.dev"
  copy_if_missing "$PRIMARY_WORKTREE/web/.env.local" "$ROOT_DIR/web/.env.local"
fi

copy_if_missing "$ROOT_DIR/.env.example" "$ROOT_DIR/.env.dev"
copy_if_missing "$ROOT_DIR/web/.env.example" "$ROOT_DIR/web/.env.local"

cat > "$ROOT_DIR/.env.vk.local" <<ENVEOF
# Auto generated by scripts/vk_setup.sh
# 本文件用于 Vibe Kanban 多 worktree 本机开发
ENV=dev
VK_GIT_BRANCH=${VK_GIT_BRANCH}
VK_BACKEND_PORT=${VK_BACKEND_PORT}
VK_FRONTEND_PORT=${VK_FRONTEND_PORT}
TEST_BACKEND_PORT=${VK_BACKEND_PORT}
TEST_FRONTEND_PORT=${VK_FRONTEND_PORT}
E2E_API_BASE=${VK_BACKEND_BASE_URL}
LIVE_API_BASE=${LIVE_API_BASE}
API_PUBLIC_URL=${VK_BACKEND_BASE_URL}/public
ENVEOF

cat > "$ROOT_DIR/web/.env.vk.local" <<ENVEOF
# Auto generated by scripts/vk_setup.sh
NEXT_PUBLIC_API_BASE_URL=${VK_BACKEND_BASE_URL}
E2E_API_BASE=${VK_BACKEND_BASE_URL}
PLAYWRIGHT_BASE_URL=${VK_FRONTEND_BASE_URL}
PLAYWRIGHT_FRONTEND_PORT=${VK_FRONTEND_PORT}
ENVEOF

echo "[vk_setup] branch=${VK_GIT_BRANCH} (main=${VK_IS_MAIN_BRANCH})"
echo "[vk_setup] backend=${VK_BACKEND_BASE_URL}"
echo "[vk_setup] frontend=${VK_FRONTEND_BASE_URL}"
echo "[vk_setup] generated: .env.vk.local, web/.env.vk.local"
