#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd -P)"
cd "$ROOT_DIR"

eval "$(bash scripts/vk_ports.sh --export)"

RUN_DIR="$ROOT_DIR/.vibe/run"
RUNTIME_VENV_LINK="$ROOT_DIR/.vibe/venv"
mkdir -p "$RUN_DIR"

PRIMARY_WORKTREE="$(git worktree list --porcelain | awk '/^worktree /{print $2; exit}')"
SHARED_VENV_MODE="${VK_SHARED_VENV_MODE:-auto}"
SHARED_VENV_PATH="${VK_SHARED_VENV_PATH:-}"
if [[ -z "$SHARED_VENV_PATH" && -n "$PRIMARY_WORKTREE" ]]; then
  SHARED_VENV_PATH="${PRIMARY_WORKTREE}/venv"
fi

copy_if_missing() {
  local src_file="$1"
  local dst_file="$2"
  if [[ ! -f "$dst_file" && -f "$src_file" ]]; then
    cp "$src_file" "$dst_file"
    echo "[vk_setup] copied: $src_file -> $dst_file"
  fi
}

has_local_posix_venv() {
  [[ -x "$ROOT_DIR/venv/bin/uvicorn" ]]
}

has_shared_venv() {
  [[ -n "$SHARED_VENV_PATH" && -x "$SHARED_VENV_PATH/bin/uvicorn" ]]
}

ensure_shared_venv() {
  if [[ "$SHARED_VENV_MODE" == "off" ]]; then
    echo "[vk_setup] skip shared venv (VK_SHARED_VENV_MODE=off)"
    return 0
  fi

  if has_local_posix_venv; then
    echo "[vk_setup] venv ready: $ROOT_DIR/venv"
    return 0
  fi

  if has_shared_venv; then
    if [[ -e "$ROOT_DIR/venv" ]]; then
      if [[ -d "$ROOT_DIR/venv/Scripts" && ! -d "$ROOT_DIR/venv/bin" ]]; then
        echo "[vk_setup] detected non-posix local venv, will use shared venv through .vibe/venv"
      else
        echo "[vk_setup] local venv unavailable, will use shared venv through .vibe/venv"
      fi
    else
      echo "[vk_setup] local venv missing, will use shared venv through .vibe/venv"
    fi
    return 0
  fi

  if [[ "$SHARED_VENV_MODE" == "always" ]]; then
    echo "[vk_setup] shared venv required but unavailable: $SHARED_VENV_PATH" >&2
    exit 1
  fi

  if [[ -e "$ROOT_DIR/venv" ]]; then
    echo "[vk_setup] detected local venv but uvicorn missing: $ROOT_DIR/venv"
  else
    echo "[vk_setup] shared venv unavailable, keep local installation flow"
  fi
}

ensure_runtime_venv_link() {
  local link_target=""

  if [[ "$SHARED_VENV_MODE" != "off" ]] && has_shared_venv && ! has_local_posix_venv; then
    link_target="$SHARED_VENV_PATH"
  fi

  if [[ -z "$link_target" ]]; then
    if [[ -L "$RUNTIME_VENV_LINK" ]]; then
      rm "$RUNTIME_VENV_LINK"
      echo "[vk_setup] removed runtime venv link: $RUNTIME_VENV_LINK"
    fi
    return 0
  fi

  if [[ -L "$RUNTIME_VENV_LINK" ]]; then
    local current_target
    current_target="$(readlink "$RUNTIME_VENV_LINK")"
    if [[ "$current_target" == "$link_target" ]]; then
      echo "[vk_setup] runtime venv link already points to: $current_target"
      return 0
    fi
    rm "$RUNTIME_VENV_LINK"
  elif [[ -e "$RUNTIME_VENV_LINK" ]]; then
    echo "[vk_setup] skip runtime venv link update because target exists: $RUNTIME_VENV_LINK"
    return 0
  fi

  ln -s "$link_target" "$RUNTIME_VENV_LINK"
  echo "[vk_setup] runtime venv link: $RUNTIME_VENV_LINK -> $link_target"
}

if [[ -n "$PRIMARY_WORKTREE" && "$PRIMARY_WORKTREE" != "$ROOT_DIR" ]]; then
  copy_if_missing "$PRIMARY_WORKTREE/.env.dev" "$ROOT_DIR/.env.dev"
  copy_if_missing "$PRIMARY_WORKTREE/web/.env.local" "$ROOT_DIR/web/.env.local"
fi

copy_if_missing "$ROOT_DIR/.env.example" "$ROOT_DIR/.env.dev"
copy_if_missing "$ROOT_DIR/web/.env.example" "$ROOT_DIR/web/.env.local"

ensure_shared_venv
ensure_runtime_venv_link

cat > "$ROOT_DIR/.env.vk.local" <<ENVEOF
# Auto generated by scripts/vk_setup.sh
# 本文件用于 Vibe Kanban 多 worktree 本机开发
ENV=dev
VK_GIT_BRANCH=${VK_GIT_BRANCH}
VK_BACKEND_PORT=${VK_BACKEND_PORT}
VK_FRONTEND_PORT=${VK_FRONTEND_PORT}
VK_SHARED_VENV_MODE=${SHARED_VENV_MODE}
VK_SHARED_VENV_PATH=${SHARED_VENV_PATH}
VK_RUNTIME_VENV=${RUNTIME_VENV_LINK}
TEST_BACKEND_PORT=${VK_BACKEND_PORT}
TEST_FRONTEND_PORT=${VK_FRONTEND_PORT}
E2E_API_BASE=${VK_BACKEND_BASE_URL}
LIVE_API_BASE=${LIVE_API_BASE}
API_PUBLIC_URL=${VK_BACKEND_BASE_URL}/public
ENVEOF

cat > "$ROOT_DIR/web/.env.vk.local" <<ENVEOF
# Auto generated by scripts/vk_setup.sh
NEXT_PUBLIC_API_BASE_URL=${VK_BACKEND_BASE_URL}
E2E_API_BASE=${VK_BACKEND_BASE_URL}
PLAYWRIGHT_BASE_URL=${VK_FRONTEND_BASE_URL}
PLAYWRIGHT_FRONTEND_PORT=${VK_FRONTEND_PORT}
ENVEOF

echo "[vk_setup] branch=${VK_GIT_BRANCH} (main=${VK_IS_MAIN_BRANCH})"
echo "[vk_setup] backend=${VK_BACKEND_BASE_URL}"
echo "[vk_setup] frontend=${VK_FRONTEND_BASE_URL}"
echo "[vk_setup] shared_venv_mode=${SHARED_VENV_MODE}"
echo "[vk_setup] shared_venv_path=${SHARED_VENV_PATH}"
echo "[vk_setup] runtime_venv=${RUNTIME_VENV_LINK}"
echo "[vk_setup] generated: .env.vk.local, web/.env.vk.local"
